# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from backend_server.grpc_config import msg_transfer_pb2 as server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2


class MsgTransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.image_processor = channel.unary_unary(
                '/MsgTransfer/image_processor',
                request_serializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.MsgRequest.SerializeToString,
                response_deserializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.MsgReply.FromString,
                )
        self.get_server_utilization = channel.unary_unary(
                '/MsgTransfer/get_server_utilization',
                request_serializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Server_Utilization_Request.SerializeToString,
                response_deserializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Server_Utilization_Reply.FromString,
                )
        self.get_loaded_models_name = channel.unary_unary(
                '/MsgTransfer/get_loaded_models_name',
                request_serializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Loaded_Model_Name_Request.SerializeToString,
                response_deserializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Loaded_Model_Name_Reply.FromString,
                )
        self.load_specified_model = channel.unary_unary(
                '/MsgTransfer/load_specified_model',
                request_serializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Load_Specified_Model_Request.SerializeToString,
                response_deserializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Load_Specified_Model_Reply.FromString,
                )


class MsgTransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def image_processor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_server_utilization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_loaded_models_name(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def load_specified_model(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'image_processor': grpc.unary_unary_rpc_method_handler(
                    servicer.image_processor,
                    request_deserializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.MsgRequest.FromString,
                    response_serializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.MsgReply.SerializeToString,
            ),
            'get_server_utilization': grpc.unary_unary_rpc_method_handler(
                    servicer.get_server_utilization,
                    request_deserializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Server_Utilization_Request.FromString,
                    response_serializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Server_Utilization_Reply.SerializeToString,
            ),
            'get_loaded_models_name': grpc.unary_unary_rpc_method_handler(
                    servicer.get_loaded_models_name,
                    request_deserializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Loaded_Model_Name_Request.FromString,
                    response_serializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Loaded_Model_Name_Reply.SerializeToString,
            ),
            'load_specified_model': grpc.unary_unary_rpc_method_handler(
                    servicer.load_specified_model,
                    request_deserializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Load_Specified_Model_Request.FromString,
                    response_serializer=server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Load_Specified_Model_Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MsgTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MsgTransfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def image_processor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MsgTransfer/image_processor',
            server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.MsgRequest.SerializeToString,
            server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.MsgReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_server_utilization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MsgTransfer/get_server_utilization',
            server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Server_Utilization_Request.SerializeToString,
            server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Server_Utilization_Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_loaded_models_name(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MsgTransfer/get_loaded_models_name',
            server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Loaded_Model_Name_Request.SerializeToString,
            server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Loaded_Model_Name_Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def load_specified_model(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MsgTransfer/load_specified_model',
            server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Load_Specified_Model_Request.SerializeToString,
            server_dot_grpc__config_dot_protos_dot_msg__transfer__pb2.Load_Specified_Model_Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
