# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/grpc_section/protos/msg_transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server/grpc_section/protos/msg_transfer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-server/grpc_section/protos/msg_transfer.proto\"?\n\nMsgRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\r\n\x05\x66rame\x18\x02 \x01(\t\x12\x13\n\x0b\x66rame_shape\x18\x03 \x01(\t\"/\n\x08MsgReply\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\x13\n\x0b\x66rame_shape\x18\x03 \x01(\t\"\x13\n\x11\x43pu_Usage_Request\"$\n\x0f\x43pu_Usage_Reply\x12\x11\n\tcpu_usage\x18\x01 \x01(\x02\x32s\n\x0bMsgTransfer\x12+\n\x0fImageProcessing\x12\x0b.MsgRequest\x1a\t.MsgReply\"\x00\x12\x37\n\rGet_Cpu_Usage\x12\x12.Cpu_Usage_Request\x1a\x10.Cpu_Usage_Reply\"\x00\x62\x06proto3'
)




_MSGREQUEST = _descriptor.Descriptor(
  name='MsgRequest',
  full_name='MsgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='MsgRequest.model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame', full_name='MsgRequest.frame', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_shape', full_name='MsgRequest.frame_shape', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=112,
)


_MSGREPLY = _descriptor.Descriptor(
  name='MsgReply',
  full_name='MsgReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='MsgReply.result', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_shape', full_name='MsgReply.frame_shape', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=161,
)


_CPU_USAGE_REQUEST = _descriptor.Descriptor(
  name='Cpu_Usage_Request',
  full_name='Cpu_Usage_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=182,
)


_CPU_USAGE_REPLY = _descriptor.Descriptor(
  name='Cpu_Usage_Reply',
  full_name='Cpu_Usage_Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu_usage', full_name='Cpu_Usage_Reply.cpu_usage', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=220,
)

DESCRIPTOR.message_types_by_name['MsgRequest'] = _MSGREQUEST
DESCRIPTOR.message_types_by_name['MsgReply'] = _MSGREPLY
DESCRIPTOR.message_types_by_name['Cpu_Usage_Request'] = _CPU_USAGE_REQUEST
DESCRIPTOR.message_types_by_name['Cpu_Usage_Reply'] = _CPU_USAGE_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgRequest = _reflection.GeneratedProtocolMessageType('MsgRequest', (_message.Message,), {
  'DESCRIPTOR' : _MSGREQUEST,
  '__module__' : 'server.grpc_section.protos.msg_transfer_pb2'
  # @@protoc_insertion_point(class_scope:MsgRequest)
  })
_sym_db.RegisterMessage(MsgRequest)

MsgReply = _reflection.GeneratedProtocolMessageType('MsgReply', (_message.Message,), {
  'DESCRIPTOR' : _MSGREPLY,
  '__module__' : 'server.grpc_section.protos.msg_transfer_pb2'
  # @@protoc_insertion_point(class_scope:MsgReply)
  })
_sym_db.RegisterMessage(MsgReply)

Cpu_Usage_Request = _reflection.GeneratedProtocolMessageType('Cpu_Usage_Request', (_message.Message,), {
  'DESCRIPTOR' : _CPU_USAGE_REQUEST,
  '__module__' : 'server.grpc_section.protos.msg_transfer_pb2'
  # @@protoc_insertion_point(class_scope:Cpu_Usage_Request)
  })
_sym_db.RegisterMessage(Cpu_Usage_Request)

Cpu_Usage_Reply = _reflection.GeneratedProtocolMessageType('Cpu_Usage_Reply', (_message.Message,), {
  'DESCRIPTOR' : _CPU_USAGE_REPLY,
  '__module__' : 'server.grpc_section.protos.msg_transfer_pb2'
  # @@protoc_insertion_point(class_scope:Cpu_Usage_Reply)
  })
_sym_db.RegisterMessage(Cpu_Usage_Reply)



_MSGTRANSFER = _descriptor.ServiceDescriptor(
  name='MsgTransfer',
  full_name='MsgTransfer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=222,
  serialized_end=337,
  methods=[
  _descriptor.MethodDescriptor(
    name='ImageProcessing',
    full_name='MsgTransfer.ImageProcessing',
    index=0,
    containing_service=None,
    input_type=_MSGREQUEST,
    output_type=_MSGREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Get_Cpu_Usage',
    full_name='MsgTransfer.Get_Cpu_Usage',
    index=1,
    containing_service=None,
    input_type=_CPU_USAGE_REQUEST,
    output_type=_CPU_USAGE_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSGTRANSFER)

DESCRIPTOR.services_by_name['MsgTransfer'] = _MSGTRANSFER

# @@protoc_insertion_point(module_scope)
